import { Suspense } from "react";
import { prisma } from "@/lib/prisma";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/landing/footer";
import { TrendCard } from "@/components/trend/trend-card";
import { TrendFilters } from "@/components/trend/trend-filters";
import { TrendingUp } from "lucide-react";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Khongbeng AI Trend — Investment News",
  description: "AI-powered investment trend analysis. Stay updated with the latest global market insights generated every 6 hours.",
};

async function getArticles(category?: string) {
  return prisma.trendArticle.findMany({
    where: category ? { category } : undefined,
    orderBy: { publishedAt: "desc" },
    take: 30,
  });
}

export default async function TrendPage({
  searchParams,
}: {
  searchParams: Promise<{ category?: string }>;
}) {
  const params = await searchParams;
  const articles = await getArticles(params.category);

  return (
    <main className="min-h-screen bg-background">
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-96 h-96 bg-emerald-500/5 rounded-full blur-3xl" />
        <div className="absolute top-1/3 -left-40 w-96 h-96 bg-gold-500/5 rounded-full blur-3xl" />
      </div>

      <Navbar />

      {/* Header */}
      <section className="relative pt-28 pb-12 px-6">
        <div className="max-w-5xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-500/10 border border-emerald-500/20 mb-6">
            <TrendingUp className="w-4 h-4 text-emerald-400" />
            <span className="text-sm text-emerald-400 font-medium">AI-Powered Analysis</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4">
            Khongbeng AI <span className="text-emerald-400">Trend</span>
          </h1>
          <p className="text-muted-foreground max-w-xl mx-auto">
            Investment trend analysis generated by AI every 6 hours. Stay ahead of the market with real-time insights.
          </p>
        </div>
      </section>

      {/* Filters */}
      <Suspense>
        <TrendFilters activeCategory={params.category} />
      </Suspense>

      {/* Articles Grid */}
      <section className="max-w-5xl mx-auto px-6 pb-20">
        {articles.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {articles.map((article) => (
              <TrendCard
                key={article.id}
                article={{
                  ...article,
                  publishedAt: article.publishedAt.toISOString(),
                }}
              />
            ))}
          </div>
        ) : (
          <div className="text-center py-20">
            <TrendingUp className="w-12 h-12 text-muted-foreground/30 mx-auto mb-4" />
            <p className="text-muted-foreground">No articles yet. Check back soon!</p>
          </div>
        )}
      </section>

      <Footer />
    </main>
  );
}
